name: Up
on: workflow_dispatch

jobs:
  up:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Up
        run: |
          set -ex

          git clone https://github.com/denverquane/automuteus.git
          pushd automuteus

          base=https://github.com/docker/machine/releases/download/v0.16.2 && \
          curl -L $base/docker-machine-$(uname -s)-$(uname -m) >/tmp/docker-machine && \
          sudo mv /tmp/docker-machine /usr/local/bin/docker-machine && \
          chmod +x /usr/local/bin/docker-machine

          docker-machine create \
              --driver digitalocean \
              --digitalocean-access-token \
              ${{ secrets.DIGITAL_OCEAN_ACCESS_TOKEN }} \
              --engine-install-url "https://releases.rancher.com/install-docker/19.03.9.sh" \
              automuteus

          eval $(docker-machine env automuteus --shell bash)

          cat << EOF > .env
          AUTOMUTEUS_TAG=latest
          GALACTUS_TAG=latest
          DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}
          GALACTUS_HOST=http://$(docker-machine ip automuteus)
          GALACTUS_EXTERNAL_PORT=80
          POSTGRES_USER=postgres
          POSTGRES_PASS=putsomesecretpasswordhere
          EMOJI_GUILD_ID=
          WORKER_BOT_TOKENS=
          CAPTURE_TIMEOUT=
          AUTOMUTEUS_LISTENING=
          BROKER_PORT=8123
          GALACTUS_PORT=5858
          GALACTUS_REDIS_ADDR=redis:6379
          AUTOMUTEUS_REDIS_ADDR=redis:6379
          GALACTUS_ADDR=http://galactus:5858
          POSTGRES_ADDR=postgres:5432
          EOF
          cat .env

          docker-compose up -d
          popd

      - name: Upload Docker Machine
        uses: actions/upload-artifact@v2
        with:
          name: docker-machine
          path: ~/.docker/machine

      - name: Discord Notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: "AutoMuteUs is running."
